spring.application.name=appliweb
# URL de connexion à votre base recensement
# 3306 étant le port MySQL par défaut
spring.datasource.url=jdbc:mysql://localhost:3306/recensement?useSSL=false&serverTimezone=UTC

# Identifiants de connexion MySQL (ici, root sans mot de passe)
spring.datasource.username=root
spring.datasource.password=

